name: Deploy Website

on:
  push:
    branches:
      - main  # أو اسم الفرع الخاص بك

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject Google Script URL
        run: |
          sed -i "s|YOUR_GOOGLE_SCRIPT_WEB_APP_URL_HERE|${{ secrets.GOOGLE_SHEET_LINK }}|g" js/script.js

      - name: Deploy to GitHub Pages (Optional)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
